version: '3'

services:
  react:
    image: akhileshpatel123/react-app
    container_name: react
    ports:
      - "8081:80"
    networks:
      - loki-net
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: container_name=react

  frontend:
    image: nginx:latest
    container_name: frontend
    labels:
      - "service=frontend-service"
      - "com.docker.compose.service=frontend"
    ports:
      - "8082:80"
    networks:
      - loki-net
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: container_name=frontend

volumes:
  grafana-data:
  loki-data:
  fluentbit-storage:

networks:
  loki-net:
    driver: bridge
