version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
       - "service=grafana-service"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki-net
    restart: unless-stopped
networks:
  loki-net:
    name: loki-net
    driver: bridge

volumes:
  grafana-data:

