version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      - "service=nginx-service"
    ports:
      - "8080:80"  # Exposes NGINX on localhost:8080
    networks:
      - loki-net
    restart: unless-stopped
networks:
  loki-net:
    driver: bridge

